// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for RegisterErrorType.
const (
	DuplicateEmail  RegisterErrorType = "DuplicateEmail"
	InvalidEmail    RegisterErrorType = "InvalidEmail"
	InvalidPassword RegisterErrorType = "InvalidPassword"
)

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	EndTime     *time.Time `json:"end_time,omitempty"`

	// EstimatedTime Estimated time in minutes
	EstimatedTime *int32     `json:"estimated_time,omitempty"`
	Name          string     `json:"name"`
	Priority      string     `json:"priority"`
	StartTime     *time.Time `json:"start_time,omitempty"`
	Status        string     `json:"status"`
}

// DefaultResponse defines model for DefaultResponse.
type DefaultResponse struct {
	Message *string `json:"message,omitempty"`
}

// RegisterError defines model for RegisterError.
type RegisterError struct {
	Message *string            `json:"message,omitempty"`
	Type    *RegisterErrorType `json:"type,omitempty"`
}

// RegisterErrorType defines model for RegisterError.Type.
type RegisterErrorType string

// Task defines model for Task.
type Task struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	EndTime     *time.Time `json:"end_time,omitempty"`

	// EstimatedTime Estimated time in minutes
	EstimatedTime *int32     `json:"estimated_time,omitempty"`
	Id            *int32     `json:"id,omitempty"`
	Name          *string    `json:"name,omitempty"`
	Priority      *string    `json:"priority,omitempty"`
	StartTime     *time.Time `json:"start_time,omitempty"`
	Status        *string    `json:"status,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
	UserId        *int32     `json:"user_id,omitempty"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Description *string    `json:"description,omitempty"`
	EndTime     *time.Time `json:"end_time,omitempty"`

	// EstimatedTime Estimated time in minutes
	EstimatedTime *int32     `json:"estimated_time,omitempty"`
	Name          *string    `json:"name,omitempty"`
	Priority      *string    `json:"priority,omitempty"`
	StartTime     *time.Time `json:"start_time,omitempty"`
	Status        *string    `json:"status,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	ID        *int32     `json:"id,omitempty"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = DefaultResponse

// GetAuthGoogleCallbackParams defines parameters for GetAuthGoogleCallback.
type GetAuthGoogleCallbackParams struct {
	// Code Authorization code from Google
	Code string `form:"code" json:"code"`

	// State State parameter for CSRF protection
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// PostAuthRefreshTokenJSONBody defines parameters for PostAuthRefreshToken.
type PostAuthRefreshTokenJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// PostAuthRefreshTokenParams defines parameters for PostAuthRefreshToken.
type PostAuthRefreshTokenParams struct {
	// RefreshToken Refresh token stored in cookie
	RefreshToken *string `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// PostLogoutJSONBody defines parameters for PostLogout.
type PostLogoutJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// PostLogoutParams defines parameters for PostLogout.
type PostLogoutParams struct {
	// RefreshToken Refresh token stored in cookie
	RefreshToken *string `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PostAuthRefreshTokenJSONRequestBody defines body for PostAuthRefreshToken for application/json ContentType.
type PostAuthRefreshTokenJSONRequestBody PostAuthRefreshTokenJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostLogoutJSONRequestBody defines body for PostLogout for application/json ContentType.
type PostLogoutJSONRequestBody PostLogoutJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = CreateTaskRequest

// PutTasksIdJSONRequestBody defines body for PutTasksId for application/json ContentType.
type PutTasksIdJSONRequestBody = UpdateTaskRequest
