// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get focus session analytics
	// (GET /analytics/focus)
	GetAnalyticsFocus(ctx echo.Context, params GetAnalyticsFocusParams) error
	// Initiate Google OAuth2 login flow
	// (GET /auth/google/authorize)
	GetAuthGoogleAuthorize(ctx echo.Context) error
	// Handle Google OAuth2 callback
	// (GET /auth/google/callback)
	GetAuthGoogleCallback(ctx echo.Context, params GetAuthGoogleCallbackParams) error
	// Get new access and refresh tokens using refresh token
	// (POST /auth/refresh-token)
	PostAuthRefreshToken(ctx echo.Context, params PostAuthRefreshTokenParams) error
	// Start a new focus session
	// (POST /focus-sessions)
	PostFocusSessions(ctx echo.Context) error
	// End an active focus session
	// (POST /focus-sessions/{id}/end)
	PostFocusSessionsIdEnd(ctx echo.Context, id int32) error
	// Login to the system
	// (POST /login)
	PostLogin(ctx echo.Context) error
	// Logout and invalidate refresh token
	// (POST /logout)
	PostLogout(ctx echo.Context, params PostLogoutParams) error
	// Get user profile
	// (GET /profile)
	GetProfile(ctx echo.Context) error
	// Register a new user
	// (POST /register)
	PostRegister(ctx echo.Context) error
	// Get list of user's tasks
	// (GET /tasks)
	GetTasks(ctx echo.Context, params GetTasksParams) error
	// Create a new task
	// (POST /tasks)
	PostTasks(ctx echo.Context) error
	// Delete a task
	// (DELETE /tasks/{id})
	DeleteTasksId(ctx echo.Context, id int32) error
	// Update an existing task
	// (PUT /tasks/{id})
	PutTasksId(ctx echo.Context, id int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAnalyticsFocus converts echo context to params.
func (w *ServerInterfaceWrapper) GetAnalyticsFocus(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAnalyticsFocusParams
	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_date: %s", err))
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", ctx.QueryParams(), &params.EndDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAnalyticsFocus(ctx, params)
	return err
}

// GetAuthGoogleAuthorize converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthGoogleAuthorize(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthGoogleAuthorize(ctx)
	return err
}

// GetAuthGoogleCallback converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthGoogleCallback(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthGoogleCallbackParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, true, "code", ctx.QueryParams(), &params.Code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, true, "state", ctx.QueryParams(), &params.State)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthGoogleCallback(ctx, params)
	return err
}

// PostAuthRefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthRefreshToken(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthRefreshTokenParams

	if cookie, err := ctx.Cookie("refresh_token"); err == nil {

		var value string
		err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refresh_token: %s", err))
		}
		params.RefreshToken = &value

	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthRefreshToken(ctx, params)
	return err
}

// PostFocusSessions converts echo context to params.
func (w *ServerInterfaceWrapper) PostFocusSessions(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFocusSessions(ctx)
	return err
}

// PostFocusSessionsIdEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PostFocusSessionsIdEnd(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFocusSessionsIdEnd(ctx, id)
	return err
}

// PostLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLogin(ctx)
	return err
}

// PostLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostLogout(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostLogoutParams

	if cookie, err := ctx.Cookie("refresh_token"); err == nil {

		var value string
		err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refresh_token: %s", err))
		}
		params.RefreshToken = &value

	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostLogout(ctx, params)
	return err
}

// GetProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetProfile(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProfile(ctx)
	return err
}

// PostRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostRegister(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostRegister(ctx)
	return err
}

// GetTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GetTasks(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTasksParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameter("form", true, false, "priority", ctx.QueryParams(), &params.Priority)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter priority: %s", err))
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", ctx.QueryParams(), &params.StartDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_date: %s", err))
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", ctx.QueryParams(), &params.EndDate)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_date: %s", err))
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", ctx.QueryParams(), &params.SortBy)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort_by: %s", err))
	}

	// ------------- Optional query parameter "sort_order" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_order", ctx.QueryParams(), &params.SortOrder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort_order: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTasks(ctx, params)
	return err
}

// PostTasks converts echo context to params.
func (w *ServerInterfaceWrapper) PostTasks(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTasks(ctx)
	return err
}

// DeleteTasksId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTasksId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTasksId(ctx, id)
	return err
}

// PutTasksId converts echo context to params.
func (w *ServerInterfaceWrapper) PutTasksId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutTasksId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/analytics/focus", wrapper.GetAnalyticsFocus)
	router.GET(baseURL+"/auth/google/authorize", wrapper.GetAuthGoogleAuthorize)
	router.GET(baseURL+"/auth/google/callback", wrapper.GetAuthGoogleCallback)
	router.POST(baseURL+"/auth/refresh-token", wrapper.PostAuthRefreshToken)
	router.POST(baseURL+"/focus-sessions", wrapper.PostFocusSessions)
	router.POST(baseURL+"/focus-sessions/:id/end", wrapper.PostFocusSessionsIdEnd)
	router.POST(baseURL+"/login", wrapper.PostLogin)
	router.POST(baseURL+"/logout", wrapper.PostLogout)
	router.GET(baseURL+"/profile", wrapper.GetProfile)
	router.POST(baseURL+"/register", wrapper.PostRegister)
	router.GET(baseURL+"/tasks", wrapper.GetTasks)
	router.POST(baseURL+"/tasks", wrapper.PostTasks)
	router.DELETE(baseURL+"/tasks/:id", wrapper.DeleteTasksId)
	router.PUT(baseURL+"/tasks/:id", wrapper.PutTasksId)

}

type ForbiddenJSONResponse DefaultResponse

type GetAnalyticsFocusRequestObject struct {
	Params GetAnalyticsFocusParams
}

type GetAnalyticsFocusResponseObject interface {
	VisitGetAnalyticsFocusResponse(w http.ResponseWriter) error
}

type GetAnalyticsFocus200JSONResponse FocusAnalytics

func (response GetAnalyticsFocus200JSONResponse) VisitGetAnalyticsFocusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAnalyticsFocus403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAnalyticsFocus403JSONResponse) VisitGetAnalyticsFocusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthGoogleAuthorizeRequestObject struct {
}

type GetAuthGoogleAuthorizeResponseObject interface {
	VisitGetAuthGoogleAuthorizeResponse(w http.ResponseWriter) error
}

type GetAuthGoogleAuthorize303ResponseHeaders struct {
	Location  string
	SetCookie string
}

type GetAuthGoogleAuthorize303Response struct {
	Headers GetAuthGoogleAuthorize303ResponseHeaders
}

func (response GetAuthGoogleAuthorize303Response) VisitGetAuthGoogleAuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(303)
	return nil
}

type GetAuthGoogleCallbackRequestObject struct {
	Params GetAuthGoogleCallbackParams
}

type GetAuthGoogleCallbackResponseObject interface {
	VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error
}

type GetAuthGoogleCallback200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetAuthGoogleCallback200TexthtmlResponse) VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAuthGoogleCallback301ResponseHeaders struct {
	Location string
}

type GetAuthGoogleCallback301Response struct {
	Headers GetAuthGoogleCallback301ResponseHeaders
}

func (response GetAuthGoogleCallback301Response) VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(301)
	return nil
}

type GetAuthGoogleCallback400JSONResponse DefaultResponse

func (response GetAuthGoogleCallback400JSONResponse) VisitGetAuthGoogleCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthRefreshTokenRequestObject struct {
	Params PostAuthRefreshTokenParams
	Body   *PostAuthRefreshTokenJSONRequestBody
}

type PostAuthRefreshTokenResponseObject interface {
	VisitPostAuthRefreshTokenResponse(w http.ResponseWriter) error
}

type PostAuthRefreshToken200ResponseHeaders struct {
	SetCookie string
}

type PostAuthRefreshToken200JSONResponse struct {
	Body    AuthTokens
	Headers PostAuthRefreshToken200ResponseHeaders
}

func (response PostAuthRefreshToken200JSONResponse) VisitPostAuthRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostAuthRefreshToken403Response struct {
}

func (response PostAuthRefreshToken403Response) VisitPostAuthRefreshTokenResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type PostFocusSessionsRequestObject struct {
	Body *PostFocusSessionsJSONRequestBody
}

type PostFocusSessionsResponseObject interface {
	VisitPostFocusSessionsResponse(w http.ResponseWriter) error
}

type PostFocusSessions201JSONResponse FocusSession

func (response PostFocusSessions201JSONResponse) VisitPostFocusSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostFocusSessions400Response struct {
}

func (response PostFocusSessions400Response) VisitPostFocusSessionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostFocusSessions403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostFocusSessions403JSONResponse) VisitPostFocusSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostFocusSessions404Response struct {
}

func (response PostFocusSessions404Response) VisitPostFocusSessionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostFocusSessionsIdEndRequestObject struct {
	Id   int32 `json:"id"`
	Body *PostFocusSessionsIdEndJSONRequestBody
}

type PostFocusSessionsIdEndResponseObject interface {
	VisitPostFocusSessionsIdEndResponse(w http.ResponseWriter) error
}

type PostFocusSessionsIdEnd200JSONResponse FocusSession

func (response PostFocusSessionsIdEnd200JSONResponse) VisitPostFocusSessionsIdEndResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostFocusSessionsIdEnd400Response struct {
}

func (response PostFocusSessionsIdEnd400Response) VisitPostFocusSessionsIdEndResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostFocusSessionsIdEnd403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostFocusSessionsIdEnd403JSONResponse) VisitPostFocusSessionsIdEndResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostFocusSessionsIdEnd404Response struct {
}

func (response PostFocusSessionsIdEnd404Response) VisitPostFocusSessionsIdEndResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostLoginRequestObject struct {
	Body *PostLoginJSONRequestBody
}

type PostLoginResponseObject interface {
	VisitPostLoginResponse(w http.ResponseWriter) error
}

type PostLogin200ResponseHeaders struct {
	SetCookie string
}

type PostLogin200JSONResponse struct {
	Body    AuthTokens
	Headers PostLogin200ResponseHeaders
}

func (response PostLogin200JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostLogin400Response struct {
}

func (response PostLogin400Response) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostLogoutRequestObject struct {
	Params PostLogoutParams
	Body   *PostLogoutJSONRequestBody
}

type PostLogoutResponseObject interface {
	VisitPostLogoutResponse(w http.ResponseWriter) error
}

type PostLogout200ResponseHeaders struct {
	SetCookie string
}

type PostLogout200Response struct {
	Headers PostLogout200ResponseHeaders
}

func (response PostLogout200Response) VisitPostLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type PostLogout403ResponseHeaders struct {
	SetCookie string
}

type PostLogout403Response struct {
	Headers PostLogout403ResponseHeaders
}

func (response PostLogout403Response) VisitPostLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(403)
	return nil
}

type GetProfileRequestObject struct {
}

type GetProfileResponseObject interface {
	VisitGetProfileResponse(w http.ResponseWriter) error
}

type GetProfile200JSONResponse User

func (response GetProfile200JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetProfile403JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostRegisterRequestObject struct {
	Body *PostRegisterJSONRequestBody
}

type PostRegisterResponseObject interface {
	VisitPostRegisterResponse(w http.ResponseWriter) error
}

type PostRegister201JSONResponse AuthTokens

func (response PostRegister201JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostRegister400JSONResponse RegisterError

func (response PostRegister400JSONResponse) VisitPostRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTasksRequestObject struct {
	Params GetTasksParams
}

type GetTasksResponseObject interface {
	VisitGetTasksResponse(w http.ResponseWriter) error
}

type GetTasks200JSONResponse struct {
	Data       *[]Task             `json:"data,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
}

func (response GetTasks200JSONResponse) VisitGetTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTasks400Response struct {
}

func (response GetTasks400Response) VisitGetTasksResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetTasks403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetTasks403JSONResponse) VisitGetTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostTasksRequestObject struct {
	Body *PostTasksJSONRequestBody
}

type PostTasksResponseObject interface {
	VisitPostTasksResponse(w http.ResponseWriter) error
}

type PostTasks201JSONResponse Task

func (response PostTasks201JSONResponse) VisitPostTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostTasks400JSONResponse DefaultResponse

func (response PostTasks400JSONResponse) VisitPostTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostTasks403JSONResponse struct{ ForbiddenJSONResponse }

func (response PostTasks403JSONResponse) VisitPostTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTasksIdRequestObject struct {
	Id int32 `json:"id"`
}

type DeleteTasksIdResponseObject interface {
	VisitDeleteTasksIdResponse(w http.ResponseWriter) error
}

type DeleteTasksId204Response struct {
}

func (response DeleteTasksId204Response) VisitDeleteTasksIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTasksId403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteTasksId403JSONResponse) VisitDeleteTasksIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTasksId404JSONResponse DefaultResponse

func (response DeleteTasksId404JSONResponse) VisitDeleteTasksIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutTasksIdRequestObject struct {
	Id   int32 `json:"id"`
	Body *PutTasksIdJSONRequestBody
}

type PutTasksIdResponseObject interface {
	VisitPutTasksIdResponse(w http.ResponseWriter) error
}

type PutTasksId200Response struct {
}

func (response PutTasksId200Response) VisitPutTasksIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutTasksId403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutTasksId403JSONResponse) VisitPutTasksIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PutTasksId404JSONResponse DefaultResponse

func (response PutTasksId404JSONResponse) VisitPutTasksIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get focus session analytics
	// (GET /analytics/focus)
	GetAnalyticsFocus(ctx context.Context, request GetAnalyticsFocusRequestObject) (GetAnalyticsFocusResponseObject, error)
	// Initiate Google OAuth2 login flow
	// (GET /auth/google/authorize)
	GetAuthGoogleAuthorize(ctx context.Context, request GetAuthGoogleAuthorizeRequestObject) (GetAuthGoogleAuthorizeResponseObject, error)
	// Handle Google OAuth2 callback
	// (GET /auth/google/callback)
	GetAuthGoogleCallback(ctx context.Context, request GetAuthGoogleCallbackRequestObject) (GetAuthGoogleCallbackResponseObject, error)
	// Get new access and refresh tokens using refresh token
	// (POST /auth/refresh-token)
	PostAuthRefreshToken(ctx context.Context, request PostAuthRefreshTokenRequestObject) (PostAuthRefreshTokenResponseObject, error)
	// Start a new focus session
	// (POST /focus-sessions)
	PostFocusSessions(ctx context.Context, request PostFocusSessionsRequestObject) (PostFocusSessionsResponseObject, error)
	// End an active focus session
	// (POST /focus-sessions/{id}/end)
	PostFocusSessionsIdEnd(ctx context.Context, request PostFocusSessionsIdEndRequestObject) (PostFocusSessionsIdEndResponseObject, error)
	// Login to the system
	// (POST /login)
	PostLogin(ctx context.Context, request PostLoginRequestObject) (PostLoginResponseObject, error)
	// Logout and invalidate refresh token
	// (POST /logout)
	PostLogout(ctx context.Context, request PostLogoutRequestObject) (PostLogoutResponseObject, error)
	// Get user profile
	// (GET /profile)
	GetProfile(ctx context.Context, request GetProfileRequestObject) (GetProfileResponseObject, error)
	// Register a new user
	// (POST /register)
	PostRegister(ctx context.Context, request PostRegisterRequestObject) (PostRegisterResponseObject, error)
	// Get list of user's tasks
	// (GET /tasks)
	GetTasks(ctx context.Context, request GetTasksRequestObject) (GetTasksResponseObject, error)
	// Create a new task
	// (POST /tasks)
	PostTasks(ctx context.Context, request PostTasksRequestObject) (PostTasksResponseObject, error)
	// Delete a task
	// (DELETE /tasks/{id})
	DeleteTasksId(ctx context.Context, request DeleteTasksIdRequestObject) (DeleteTasksIdResponseObject, error)
	// Update an existing task
	// (PUT /tasks/{id})
	PutTasksId(ctx context.Context, request PutTasksIdRequestObject) (PutTasksIdResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAnalyticsFocus operation middleware
func (sh *strictHandler) GetAnalyticsFocus(ctx echo.Context, params GetAnalyticsFocusParams) error {
	var request GetAnalyticsFocusRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnalyticsFocus(ctx.Request().Context(), request.(GetAnalyticsFocusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnalyticsFocus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAnalyticsFocusResponseObject); ok {
		return validResponse.VisitGetAnalyticsFocusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAuthGoogleAuthorize operation middleware
func (sh *strictHandler) GetAuthGoogleAuthorize(ctx echo.Context) error {
	var request GetAuthGoogleAuthorizeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthGoogleAuthorize(ctx.Request().Context(), request.(GetAuthGoogleAuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthGoogleAuthorize")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAuthGoogleAuthorizeResponseObject); ok {
		return validResponse.VisitGetAuthGoogleAuthorizeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAuthGoogleCallback operation middleware
func (sh *strictHandler) GetAuthGoogleCallback(ctx echo.Context, params GetAuthGoogleCallbackParams) error {
	var request GetAuthGoogleCallbackRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthGoogleCallback(ctx.Request().Context(), request.(GetAuthGoogleCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthGoogleCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAuthGoogleCallbackResponseObject); ok {
		return validResponse.VisitGetAuthGoogleCallbackResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostAuthRefreshToken operation middleware
func (sh *strictHandler) PostAuthRefreshToken(ctx echo.Context, params PostAuthRefreshTokenParams) error {
	var request PostAuthRefreshTokenRequestObject

	request.Params = params

	var body PostAuthRefreshTokenJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthRefreshToken(ctx.Request().Context(), request.(PostAuthRefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthRefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostAuthRefreshTokenResponseObject); ok {
		return validResponse.VisitPostAuthRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostFocusSessions operation middleware
func (sh *strictHandler) PostFocusSessions(ctx echo.Context) error {
	var request PostFocusSessionsRequestObject

	var body PostFocusSessionsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostFocusSessions(ctx.Request().Context(), request.(PostFocusSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFocusSessions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostFocusSessionsResponseObject); ok {
		return validResponse.VisitPostFocusSessionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostFocusSessionsIdEnd operation middleware
func (sh *strictHandler) PostFocusSessionsIdEnd(ctx echo.Context, id int32) error {
	var request PostFocusSessionsIdEndRequestObject

	request.Id = id

	var body PostFocusSessionsIdEndJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostFocusSessionsIdEnd(ctx.Request().Context(), request.(PostFocusSessionsIdEndRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostFocusSessionsIdEnd")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostFocusSessionsIdEndResponseObject); ok {
		return validResponse.VisitPostFocusSessionsIdEndResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostLogin operation middleware
func (sh *strictHandler) PostLogin(ctx echo.Context) error {
	var request PostLoginRequestObject

	var body PostLoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLogin(ctx.Request().Context(), request.(PostLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostLoginResponseObject); ok {
		return validResponse.VisitPostLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostLogout operation middleware
func (sh *strictHandler) PostLogout(ctx echo.Context, params PostLogoutParams) error {
	var request PostLogoutRequestObject

	request.Params = params

	var body PostLogoutJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostLogout(ctx.Request().Context(), request.(PostLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostLogoutResponseObject); ok {
		return validResponse.VisitPostLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProfile operation middleware
func (sh *strictHandler) GetProfile(ctx echo.Context) error {
	var request GetProfileRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfile(ctx.Request().Context(), request.(GetProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProfileResponseObject); ok {
		return validResponse.VisitGetProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostRegister operation middleware
func (sh *strictHandler) PostRegister(ctx echo.Context) error {
	var request PostRegisterRequestObject

	var body PostRegisterJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostRegister(ctx.Request().Context(), request.(PostRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRegister")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostRegisterResponseObject); ok {
		return validResponse.VisitPostRegisterResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTasks operation middleware
func (sh *strictHandler) GetTasks(ctx echo.Context, params GetTasksParams) error {
	var request GetTasksRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTasks(ctx.Request().Context(), request.(GetTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTasks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTasksResponseObject); ok {
		return validResponse.VisitGetTasksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PostTasks operation middleware
func (sh *strictHandler) PostTasks(ctx echo.Context) error {
	var request PostTasksRequestObject

	var body PostTasksJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostTasks(ctx.Request().Context(), request.(PostTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTasks")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostTasksResponseObject); ok {
		return validResponse.VisitPostTasksResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteTasksId operation middleware
func (sh *strictHandler) DeleteTasksId(ctx echo.Context, id int32) error {
	var request DeleteTasksIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTasksId(ctx.Request().Context(), request.(DeleteTasksIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTasksId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteTasksIdResponseObject); ok {
		return validResponse.VisitDeleteTasksIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutTasksId operation middleware
func (sh *strictHandler) PutTasksId(ctx echo.Context, id int32) error {
	var request PutTasksIdRequestObject

	request.Id = id

	var body PutTasksIdJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutTasksId(ctx.Request().Context(), request.(PutTasksIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutTasksId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutTasksIdResponseObject); ok {
		return validResponse.VisitPutTasksIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+wb224ct/VXCKZAWmCtXdtBHwT0wbHlRK2SCpKMPjjCghqe3WU0Q05IjuStoX8vziFn",
	"dy6cvUWSY6Rv2hnOud8P9ZlnpiiNBu0dP/7MS2FFAR4s/TpThfLn+Ah/SXCZVaVXRvNj/nNV3IBlZsaU",
	"h8KxEiwrxRz4iCt8/1sFdslHXIsC+DHPERQfcZctoBAB3ExUuefHLycjXohPqqgK/IG/lI6/RtwvS/xe",
	"aQ9zsPzhYcTPxRwGqMJXTBNpA4REGlN0bEH8MOIWXGm0A5LOe2NvlJSg8UdmtAft8U9RlrnKBFI0/tUZ",
	"er1G9xcLM37MvxmvBT8Ob934XSDlImIJONsMvskycI55cwuaKccK5ZzSc2YsU/pO5EqSiCJERPim8osr",
	"PB4UbE0J1qvAgiBoU4KGvyPPzlul55wYnllwi8ETDys5mZtfIfP4zVsLwsN7k1XuEpxTRl/AbxU438d/",
	"Y0HcTmVlRWCvq87v8T2r3zOlmYPMaOl4Tz8j/unF3LxYP339Conxwt1OlWyQvu0DVYDdQNK7g4khcf5W",
	"KQuSH39cUdZDeT0o0yvhbgdl2SIzoUrQcoqY8OXM2EJ4fsyl8PCCno4SXzivCuFh/V1bFCf1e4bvUSCF",
	"0pWH3bUTfDJBbGmVscovt3kMSuS8Pot274X1e7LpvPCV2wXTZTjZ1SRx0aB5BTKlya6P9/RYgHMYo3Zz",
	"thMtd/K0GR7aYNYnuSgdSEbnUh7HZsYyEDZfMtAS6TnI6jt0pCRE/LzRIl96laWClprOAOSNyG77L1VR",
	"WnMHBWg/FRZCCKQMlbSz+EBYK8h+CuPVnRj0Iect6Llf7AU1pTYpVL4kO526ss4bUirELPLzFkvdRNRN",
	"CT+JEtMw2jgmhpXCAuAEcoo8wUSnmali6j8U/VuEgAQgWIcWAyJbsOgCKfTGi3y6Lbhc4SkGvRCzdwIg",
	"bG1JpzARfDpxUGRPW3H0yi+R+DLKGHIq/O6R8HcHiZ2p2ycj7xafm/Ku4/QfKv2PeFXKvVVSObB7MLDN",
	"Ei9XsgSNde5HLjKv7hA1yjQHD1iRgJYgpxTtGyE6UtVGvCb1XMyVJuEMJ7fQBuzTTPTDTxmzYycMVdai",
	"85atDqD/NcWDoSCg23QMA5giGrcdTDiW7GJ6erqAuXIe7Im1xu5TF9Sw1kp9V4UWBE4KoXI+4qehN+j8",
	"PBfO3Rsr+zpOEoglUJ+uQwLN11ir7hNFvtK69ouFqBa7DTv+Uc0XfMR/Aqmqgo/4mbnfPR41OGuAvDLS",
	"kAewc2vmFhxawNtG7Dv5VFKxujOeDySz//dmf5jerGdeHxzYxwlcQAE0JZVNDhBHT6fvdvUI5ByyCiV3",
	"iTzGohGEBfum8ov1r/c12f/8z1U91kJI4e2ahYX3JZWFxtwqqGHQgCw8Wk/IWkOhdTNTqn/BMoyklJ4Z",
	"4lb5HN9d+kou2XkuNFj25vyUj/gd2FD58pdHk6MJojYlaFEqfsxf0yPM5LGVGou63RtTbYnP5kB6QY1R",
	"UXEq+TH/AfyqM6S6hqCsZ5YfPyeHfsH0ULOt0V9L5zyRA9PQ0Fv3hnXdmR6+mkwebW7Y6ZgTY0M6wVwo",
	"AplYHx3x7yavh+CvCB6vZ51N2yR5N63y4zXy6aqiEHYZ1BWbhT5qLM7njkrQ1bNrhD4WlV+M58bMc6C/",
	"jVX/hYZJtFm7AKksZN4xvwCGyQib4B/o828dy81c6bqY7BtT5Rfh6JsVoo6iXgf5pJGuUbURLUDIeohu",
	"soFeIn74b0T9itWchvbiw8VZy7z65dkl+Bdvg+v2i+HLi/dxRrzy7mFYZC9rpZ1q5ZXwwNr0Bf5mublv",
	"qg7V3tdaJvK8ns8klfaj0DKHoLL6MJtZU3SQCi1ZiNNunJs5jRdqNW/W59uahF6A6AzUW2LPjIQmHQNL",
	"BDzGm4MtbyvYqK4uWkxXwFaU0XSNtFZa4yGjU6OhWOb3Q7499Hj45McLX+TtmAOfBNZFUUqgPfUUkt0r",
	"v6gV5SpKF7Mqz5eJsNeLRJiL0ZbmIKmHbn7+MOKvJy83e9vMEtmRCDS6YOhkGsFrdnK+9zWcDxdnPVgt",
	"d1lLAZOoOx6P7+HGKQ9HmSm+aWbLfxwdHf1STSav/t7am+DjlGgo+E6ec3sU+75OrCGjN5ZGdsAK5Qrh",
	"swVvR4XgsR33zNZONhQRoiRerDZIpXGpIdxCOQZalkZpz1CoZYzoEUAMZ+SboPwCwzy9pZKb3Ri5RB5C",
	"uDv6RZ/O2I1BrVpgpQUH2o/6X3hxCw7fZyBBZ/hhL6ycG0dx5SIQchXroo1R5aJFtPPGBnNfReNk5dXe",
	"tm11aeLjeyOXe5lQuwjeZcEXq7wm/3Wn069ce2vSxyx0GrvMhHX/DPd1LJiDRhWC7ManRmzYlEBb+tuS",
	"PFclVNrXjGUQWsq2KXf8C0slDfcsxBNKfK3jjlW06LUdyhJ+RxXXi1hxuabP9Q27ORx0/HCr2qS14YXw",
	"Q3s9hImsbz4vH7dOrmfyW6vk2B/2UlSM2WltK11WHnXuhbtl2tA2oawnDQeU2/jFd4l4WYOfmUrLFsIb",
	"yI2eY66kKmmvgv0SGyUmyBJbhXvD0kKHljK18WclH8ag5R42dypPtBzo4rA/XEdH2pVvrXo2z56un8bC",
	"B7awTxwN9zNnmukfaMw1DOXIwuLO4PGsOTLRNujfa8snWjKhI7E7WTO1OJtt94yOPFb2HR4nlfVofmNK",
	"JmpO9cykEvH2yPpciTm0jjXyp8vCG0yZJD2upcpchayC7CRhkidaGxaKbuk8FOkUm5u5qfxXW86eBfL/",
	"hEVs4Hz/8rUTrxpRtG5mg0B3tOx3kIPvGsNOo5pDq81nIK3rSqbyVMfGi4miCzXtWqU1M5XDphHweTzy",
	"hAHtg6vvfCbGF5FEpnSY+lL+ffpJatXA3ZAdZcYgOxtXyJtzWL1o/uJprHkxDOJqumzupFedZyD48Ez3",
	"8pkyXVBAvCKyrrX4zqOe1bCpsfDntLZnIrcg5JLBJ+V8Y4/XWfY/jHbkpH3fIMHMRZOZ6MJUSeIHrpM6",
	"a2ixeYgD2oR/0zWxTd59RQd6uSnFyvrIeH0p/GG09XDjYntiNAvCZgvmwRY0cFQ5shVut90sGaY5DLPN",
	"jwYmtQSI7zUXft/BtrpGNzQKrtrDyt3XpNswN66zJu/RN2677ox9vQ7eiXPr6VYj+6vSWV45dQd/G5bE",
	"gQu+zUSAlruScNBWMEEA5JJucRrr2c2Q9PHt9GaZ/keG5mZ7tLr40HrY2MU3bh80dvvXO9B6iSQaKwf/",
	"14KorA+kCEV4DRIF/aKH14+/Qe1cyRBetG7xbrPd1HXhcnXlbRuExOW41N6/F4PPlGtcrqU9xRopK8AL",
	"YmSnTv45apQ80ovx/1sXyG7kgfD7GkU3WJ7U8f/pRpHNuzrPXD4ES+rrmeZ5WyaOz70lehajCRqJVQOa",
	"R8JaVmUDDRiDlWOT0ref0LyQBZ0+81SxZTBDE9tAd0rDB87Rnssm2vPm/VQcO0oxpN4RL6tULKj8F1Hk",
	"40ed/g3B3cdzCTXES5p/LiMKMmRCh/5H6flgtCCw9q62lcrmcXd/PB7nJhP5wjh//N1kMuGII36fuhgS",
	"rzxgql3ZpmvclENK+3URzQhS58MMe5RUaiG0mNP/LSU/Dcwl6sXWjD/1ZRhw979c3RdLs7a+Inb98L8A",
	"AAD//2rJOTUmPAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
