// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameToken = "token"

// Token mapped from table <token>
type Token struct {
	ID        int32      `gorm:"column:id;primaryKey" json:"id"`
	UserID    int32      `gorm:"column:user_id;not null" json:"user_id"`
	TokenHash string     `gorm:"column:token_hash;not null" json:"token_hash"`
	Purpose   string     `gorm:"column:purpose;not null" json:"purpose"`
	CreatedAt *time.Time `gorm:"column:created_at" json:"created_at"`
	ExpiresAt time.Time  `gorm:"column:expires_at;not null" json:"expires_at"`
}

// TableName Token's table name
func (*Token) TableName() string {
	return TableNameToken
}
